export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FALIURE = "FETCH_USERS_FAILURE";
export const DELETE_USER = "DELETE_USER";
export const ADD_USER = "ADD_USER";
